### PR TITLE
Modify some pattern internals, cargo fmt, some tidying.

### PR DESCRIPTION
**Pull request by cristeigabriela**
Hello, there was some issues with the tests so I didn't get to try - although, there shouldn't be any issue. If there is please tell me and I'll take care of it.

Also, why not reimplement the pattern scanner as following?

```
    /// Find `pattern` indice in `self.size`-sized raw parts of `self.bytes`, returns either
    /// `Pointer<T>` or `std::io::Error`
    ///
    /// # Arguments
    ///
    /// `pattern` - Array, can contain wildcard (`0`) which'll be ignored in matching
    ///
    /// # Example
    ///
    /// ```
    /// module.find_pattern_bytes::<u8>(b"\x55\x8B\xEC").expect("Failed finding prologue")
    /// ```
    ///
    /// # Safety
    ///
    /// Computes `from_raw_parts` from raw pointer of `self.size` and walks section,
    /// which is considered `unsafe`
    pub fn find_pattern_bytes<T>(&self, pattern: &[u8]) -> Result<Pointer<T>, Error> {
        /// Custom predicate for iterator position finder
        fn match_with_wildcard(wildcard_array: &[u8], memory_view: &[u8]) -> bool {
            !wildcard_array
                .iter()
                .zip(memory_view)
                .map(|x| if *x.0 == 0 { true } else { *x.0 == *x.1 })
                .any(|x| !x)
        }

        let indice = unsafe {
            std::slice::from_raw_parts(self.get_bytes(), self.get_size() - pattern.len())
                .windows(pattern.len())
                .position(|x| match_with_wildcard(pattern, x))
                .ok_or(Error::new(
                    ErrorKind::InvalidData,
                    format_args!(
                        "Failed finding subsequence {:x?} in slice sequence",
                        pattern
                    )
                    .to_string(),
                ))?
        };

        Ok(Pointer::new((self.get_bytes() as usize + indice) as _))
    }

    /// This is a wrapper for it's [base function](Module::find_pattern_bytes)
    ///
    /// # Arguments
    ///
    /// `pattern` - String which'll get split by whitespaces. If a resulting substring
    /// contains `'?'`, it'll be mapped to `0` in the iterator, otherwise, it'll be turned into it's
    /// hexadecimal form. If it's not contained within hexadecimal alphanumerical bounds, it'll
    /// panic
    pub fn find_pattern<T>(&self, pattern: &str) -> Result<Pointer<T>, Error> {
        fn string_to_vec(pattern: &str) -> Vec<u8> {
            pattern
                .split_whitespace()
                .map(|x| {
                    if x.contains('?') {
                        0
                    } else {
                        u8::from_str_radix(x, 16)
                            .expect("Substring not contained within hexadecimal alphanumeric form")
                    }
                })
                .collect()
        }

        self.find_pattern_bytes(string_to_vec(pattern).as_slice())
    }
```

I do it like that personally. Should also work on externals with little modification inside the find_pattern_bytes based on cfg.

### CODE REVIEW

**Comment by cristeigabriela** [comment]
Edit: I have now tested and examples work just fine!

**Comment by vxcall** [comment]
Hi, first and foremost, I'm grateful to the pull request. Since I'm not a good coder, the code may look scuffed tbh. It's thankful for me to spot redundant parts and refactor them by others. I'll review your PR later and get back to you! Thanks :relaxed:

**Comment by cristeigabriela** [comment]
Hi, it's all cool, one of the things you could do to make your Rust development experience better is simply having format-on-save. If you use VS Code, you can add this to your settings.json

```
    "[rust]": {
        "editor.defaultFormatter": "statiolake.vscode-rustfmt"
    },
    "editor.formatOnType": true,
    "editor.formatOnSave": true,
```

And it should run `cargo fmt`

**Comment by vxcall** [comment]
Having auto format off is just my personal preference. It looks unclear to me when the method chain is folded at each dot. 
It's fine to turn it on but I'm not sure if CLion, my IDE, has the auto formatting setting.

**Comment by vxcall** [comment]
Hey mate I just tried out your PR, and surprisingly pattern_scan_all_test became super faster than before. Originally, it was ridiculously slow idk why.
What do you think was the cause of the slow speed?

**Comment by cristeigabriela** [comment]
> Hey mate I just tried out your PR, and surprisingly pattern_scan_all_test became super faster than before. Originally, it was ridiculously slow idk why. What do you think was the cause of the slow speed?

Not certain, maybe optimizations ramping up on more idiomatic approaches?

**Comment by vxcall** [comment]
Alright it looks pretty good to me overall, i'll merge it.
> Also, why not reimplement the pattern scanner as following?

I'll take your pattern scanning code into account as well.
Thanks mate!

**Pull request merged**
